Repository njaLocer/Locer-Android-Client, pull requests merged in 2020-10, with the labels that each got.

#15 feat: Create GenericApiResponse.kt
  app/build.gradle.kts
  app/src/main/java/org/locer/in/GenericApiResponse.kt
  buildSrc/src/main/kotlin/deps/implementations/Framework.kt
  buildSrc/src/main/kotlin/deps/versions/Framework.kt
Labels: feature

#16 feat: Added core Concepts of AndroidNavigation via Jetpack
  docs/NavConcepts.md
Labels: feature

#14 feat: Create LiveDataCallAdapter.kt
  app/src/main/java/org/locer/in/LiveDataCallAdapter.kt
Labels: feature

#18 feat: Recycler View Added
  app/src/main/java/org/locer/in/HomeFragment.kt
  app/src/main/java/org/locer/in/WishlistFragment.kt
  app/src/main/java/org/locer/in/recyclerView/Affirmation.kt
  app/src/main/java/org/locer/in/recyclerView/Datasource.kt
  app/src/main/java/org/locer/in/recyclerView/ItemAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/list_item.xml
  app/src/main/res/values/strings.xml
Labels: feature

#22 fix: Fix RecyclerView Overlaps with BottomNavBar
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
Labels: Fix

#13 chore: Added LiveDataCallAdapterFactory
  app/build.gradle.kts
  app/src/main/java/org/locer/in/utils/LiveDataCallAdapterFactory.kt
  buildSrc/src/main/kotlin/AndroidConfigs.kt
  buildSrc/src/main/kotlin/deps/implementations/Framework.kt
  buildSrc/src/main/kotlin/deps/versions/Framework.kt
Labels: chore, hacktoberfest
